sisaih:
  executable_path: 'C:/DATASUS/SISAIH01/SISAIH01.EXE'
  window_title_regex: '.*SISAIH.*'

timeouts:
  app_start: 30
  import_file: 600
  consistir: 1800
  apurar: 1800
  exportar: 300

export:
  dir: 'C:\exports'

api:
  base_url: 'http://localhost:3333'

aws:
  region: 'sa-east-1'
  sqs_queue_url: 'SUA_QUEUE_URL_AQUI'
